FROM wurstmeister/kafka

ADD messages.txt /
ADD send_messages.sh /
ADD create_topics.sh /
ADD mmchangetopic-1.0-SNAPSHOT.jar /opt/kafka/bin
ADD consumer.properties /opt/kafka/bin
ADD producer.properties /opt/kafka/bin
